### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by SAGGSOC** [chiphuyen/tf-stanford-tutorials#115]
(tensorflow) C:\Users\Sagar\stanford-tensorflow-tutorials\2017\assignments\chatbot>python data.py
Preparing raw data into train set and test set ...
Traceback (most recent call last):
  File "data.py", line 255, in <module>
    prepare_raw_data()
  File "data.py", line 178, in prepare_raw_data
    id2line = get_lines()
  File "data.py", line 34, in get_lines
    parts = line.split(' +++$+++ ')
TypeError: a bytes-like object is required, not 'str'

**Comment by MartinAbilev** [comment]
change  rb    to just r in file open line.  there all files is text data not binary. look on similar issues here resolved alredy
