### ISSUE TITLE
could not get it to work, here's my errors:

### ISSUE THREAD

**Issue by bobstheman** [chiphuyen/tf-stanford-tutorials#139]
Traceback (most recent call last):
  File "chatbot.py", line 254, in <module>
    main()
  File "chatbot.py", line 249, in main
    train()
  File "chatbot.py", line 127, in train
    test_buckets, data_buckets, train_buckets_scale = _get_buckets()
  File "chatbot.py", line 85, in _get_buckets
    test_buckets = data.load_data('test_ids.enc', 'test_ids.dec')
  File "C:\Users\Olga\Anaconda3\envs\tensorflowbot\data.py", line 193, in load_data
    encode_file = open(os.path.join(config.PROCESSED_PATH, enc_filename), 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'processed\\test_ids.enc'

**Comment by aarnphm** [comment]
run python data.py first
