### ISSUE TITLE
TypeError: Fetch argument None has invalid type <type 'NoneType'>

### ISSUE THREAD

**Issue by iairose** [chiphuyen/tf-stanford-tutorials#24]
python style_transfer.py
Dataset ready
2017-06-12 09:57:17.190398: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-12 09:57:17.374553: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-12 09:57:17.374598: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-12 09:57:17.374646: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "style_transfer.py", line 195, in <module>
    main()
  File "style_transfer.py", line 184, in main
    input_image, content_image, style_image)
  File "style_transfer.py", line 102, in _create_losses
    p = sess.run(model[CONTENT_LAYER])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 969, in _run
    fetch_handler = _FetchHandler(self._graph, fetches, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 408, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 227, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <type 'NoneType'>

**Comment by NicGian** [comment]
I had exaclty the same error, and then I found I made a mistake in modifing a function. When then I corrected the function it worked fine with python 2.7 and TF1.0. Can you post your code?

**Comment by chiphuyen** [comment]
@iairose You probably didn't return the value for one of your function. Anyway, you can try with the updated code now.
